version: "3"
services:
  nginx-service:
    container_name: nginx-container
    build: ./requirements/nginx/
    ports:
      - "443:443"
  wordpress-service:
    container_name: wordpress-container
    build: ./requirements/wordpress/
    volumes:
      - wpVolume:/var/lib/mysql
    depends_on:
      - maria-db
  maria-db:
    container_name: mariadb-cont
    build: ./requirements/mariadb/
    ports:
      - "3306:3306"
