version: "3"
services:
  nginx-service:
    depends_on:
      - wordpress-service
    container_name: nginx-container
    build: ./requirements/nginx/
    env_file:
      - .env
    volumes:
      - wpVolume:/var/www/html
    restart: on-failure
    networks:
      - net
    ports:
      - "443:443"
  wordpress-service:
    depends_on:
      - maria-db
    container_name: wordpress-container
    build: ./requirements/wordpress/
    env_file:
      - .env
    volumes:
      - wpVolume:/var/www/html
    restart: on-failure
    ports:
      - "9000:9000"
    networks:
      - net
  maria-db:
    container_name: mariadb-cont
    build: ./requirements/mariadb/
    env_file:
      - .env
    volumes:
      - mysql:/var/lib/mysql
    restart: on-failure
    ports:
      - "3306:3306"
    networks:
      - net
volumes:
  wpVolume:
  mysql:
networks:
  net:
